# Generated by Django 4.2.7 on 2023-12-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
